name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: rust:1-slim
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --workspace --locked
      - name: Test
        run: cargo test --workspace --locked
      - name: Format
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --workspace --all-targets -- -D warnings
